# Generated by Django 4.2.7 on 2023-11-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matrix', '0002_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignedUsers',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_assignedProjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='associatedMatrix',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associatedProject', to='matrix.matrix'),
        ),
    ]
