# Generated by Django 4.2.7 on 2023-11-23 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
        ('matrix', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='associated_matrix',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_associated_project', to='matrix.matrix'),
        ),
    ]
