# Generated by Django 4.2.7 on 2023-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionType', models.CharField(choices=[('Delete', 'Delete'), ('Edit Role', 'Edit Role'), ('Login', 'Login')], max_length=10)),
                ('userFullNameExec', models.CharField(max_length=255)),
                ('userFullNameAffected', models.CharField(blank=True, max_length=255)),
                ('userRoleExec', models.CharField(max_length=50)),
                ('userRoleAffected', models.CharField(blank=True, max_length=50)),
                ('appModel', models.CharField(max_length=255)),
                ('serverTimestamp', models.DateTimeField(auto_now_add=True)),
                ('clientLocalTimestamp', models.DateTimeField()),
            ],
        ),
    ]
