# Generated by Django 4.2.7 on 2023-12-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='appModel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='clientLocalTimestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='userFullNameExec',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventrecord',
            name='userRoleExec',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
