# Generated by Django 4.2.7 on 2023-12-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventrecord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrecord',
            name='userFullNameAffected',
        ),
        migrations.RemoveField(
            model_name='eventrecord',
            name='userRoleAffected',
        ),
    ]
