# Generated by Django 4.2.7 on 2023-12-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventrecord', '0003_rename_appmodel_eventrecord_modelaffected'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrecord',
            name='data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
