# Generated by Django 4.2.7 on 2023-12-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_teammembertprofile_teammemberprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuestProfile',
        ),
        migrations.DeleteModel(
            name='TeamMemberProfile',
        ),
    ]
