# Generated by Django 4.2.7 on 2023-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_teammemberprofile_user_delete_guestprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Team Member', 'Teammember'), ('Guest', 'Guest')], max_length=50),
        ),
    ]
