# Generated by Django 4.2.7 on 2023-12-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_guest_delete_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='assignedProjects',
            new_name='projects',
        ),
    ]
