# Generated by Django 4.2.7 on 2023-12-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='isDraft',
            new_name='isPublished',
        ),
    ]
