# Generated by Django 4.2.7 on 2023-12-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_isdraft_project_ispublished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
