# Generated by Django 4.2.7 on 2023-12-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_project_owner_project_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='recordsValuesIds',
            field=models.IntegerField(default=0),
        ),
    ]
