# Generated by Django 4.2.7 on 2023-12-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_project_recordsvaluesids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='recordsValuesIds',
            new_name='recordIdValues',
        ),
    ]
