# Generated by Django 4.2.7 on 2023-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='keyRelationships',
        ),
        migrations.AddField(
            model_name='record',
            name='keyRelationships',
            field=models.ManyToManyField(blank=True, related_name='relations', to='record.record'),
        ),
    ]
