# Generated by Django 4.2.7 on 2023-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_record_keyrelationships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='keyRelationships',
            field=models.ManyToManyField(blank=True, to='record.record'),
        ),
    ]
