# Generated by Django 4.2.7 on 2023-11-23 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_project_id', models.CharField(max_length=255)),
                ('sprint', models.CharField(max_length=255)),
                ('artifact_name', models.CharField(max_length=255)),
                ('url_resource', models.URLField(blank=True, null=True)),
                ('location_resource', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('key_relationship', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('update_date', models.DateField()),
                ('impact', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('associated_matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_records', to='matrix.matrix')),
            ],
        ),
    ]
