# Generated by Django 4.2.7 on 2023-11-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
