# Generated by Django 4.2.7 on 2023-12-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='impact',
            field=models.CharField(choices=[('NA', 'NA'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='phase',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('INITIATION', 'Initiation'), ('DEVELOPMENT', 'Development')], max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('IMPLEMENTED', 'Implemented'), ('VERIFYING', 'Verifying'), ('APPROVED', 'Approved')], max_length=255),
        ),
    ]
