# Generated by Django 4.2.7 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_record_impact_alter_record_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='impact',
            field=models.CharField(choices=[('NA', 'NA'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='phase',
            field=models.CharField(choices=[('Approval', 'Approval'), ('Initiation', 'Initiation'), ('Development', 'Development')], max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Implemented', 'Implemented'), ('Verifying', 'Verifying'), ('Approved', 'Approved')], max_length=255),
        ),
    ]
