# Generated by Django 4.2.7 on 2023-12-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
