# Generated by Django 4.2.7 on 2023-11-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_customprojectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='locationResource',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
