# Generated by Django 4.2.7 on 2023-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_remove_record_responsible_record_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='URLResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='locationResource',
        ),
        migrations.RemoveField(
            model_name='record',
            name='urlResource',
        ),
        migrations.AddField(
            model_name='record',
            name='locationResources',
            field=models.ManyToManyField(blank=True, null=True, to='record.locationresource'),
        ),
        migrations.AddField(
            model_name='record',
            name='urlResources',
            field=models.ManyToManyField(blank=True, null=True, to='record.urlresource'),
        ),
    ]
