# Generated by Django 4.2.7 on 2023-11-30 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_record_locationresources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='locationResources',
        ),
        migrations.RemoveField(
            model_name='record',
            name='urlResources',
        ),
        migrations.DeleteModel(
            name='LocationResource',
        ),
        migrations.DeleteModel(
            name='URLResource',
        ),
        migrations.AddField(
            model_name='resource',
            name='recordAssociated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associatedResources', to='record.record'),
        ),
    ]
