# Generated by Django 4.2.7 on 2023-12-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_resourcefile_resourceurl_delete_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='record.record'),
        ),
        migrations.AlterField(
            model_name='resourceurl',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='record.record'),
        ),
    ]
